version: '3.8'

services:
  backend:
    build: ./emptycup-api
    container_name: emptycup-backend
    ports:
      - "5000:5000"
    networks:
      - emptycup-net

  frontend:
    build: .
    container_name: emptycup-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - emptycup-net

networks:
  emptycup-net:
    driver: bridge
